config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get "informations", to: "pages#informations"
  get "inscription", to: "pages#inscription"

  resources :user_challenges, only: [:index, :show]
  patch "user_challenges/:id", to: "user_challenges#status", as: :change_status_user_challenge
  resources :user_designs

  get "design", to: "designs#form", as: :form_design
  post "design", to: "designs#scrap"

  get "try_design", to: "new_designs#form_without_design"
  post "try_design_post", to: "new_designs#new_design", as: :try_design_post
  get "design/:id", to: "designs#show", as: :design_show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :design
  has_many :user_challenges
end

app/models/design.rb
class Design < ApplicationRecord
  has_many :user_designs
  has_many :challenges
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :design
  has_many :challenges
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :user_design
  has_many :user_challenges
end

app/models/user_challenge.rb
class UserChallenge < ApplicationRecord
  belongs_to :user
  belongs_to :challenge
  STATUSES = [:nul, :moyen, :réussi]
end

app/models/user_design.rb
class UserDesign < ApplicationRecord
  belongs_to :user
  belongs_to :design
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    @challenges = Challenge.all
  end

  def show
    @challenge = Challenge.find(params[:id])
  end

  def edit
    @challenge = Challenge.find(params[:id])
  end

  def update
    @challenge = Challenge.find(params[:id])
    @challenge.update
    redirect_to challenge_path(@challenge)
  end

  private

  def challenge_params
    params.require(:challenge).permit(:description, :title, :theme_id)
  end
end

app/controllers/designs_controller.rb
require 'open-uri'
require 'json'

class DesignsController < ApplicationController
  def form
  end

  def scrap
    current_user.update(username: params[:name], city: params[:city])

# if params date n'est pas présent, j'en met un par default pour pas faire planter l'url


    url = "https://api.bodygraphchart.com/v221006/hd-data?api_key=#{ENV["API_KEY"]}&date=#{params[:year]}-#{params[:month]}-#{params[:day]}-#{params[:hour]}-#{params[:minutes]}"
# heure par default
    design = JSON.parse(URI.open("#{url}").read)

# je vais chercher l'ID à chaque fois sur chaque hash (exemple: strategie, propriete, innerautority)(https://bodygraphchart.com/docs/)

    strategy = design["Properties"]["Strategy"]["id"]
    type = design["Properties"]["Type"]["id"]
    authority = design["Properties"]["InnerAuthority"]["id"]
    notself = design["Properties"]["NotSelfTheme"]["id"]

    design_from_api = Design.create(name_type: type, strategy: strategy, authority: authority, notself: notself )

    user_design = UserDesign.new(design_id: design_from_api.id, user_id: current_user.id)
    user_design.save

    redirect_to user_design_path(user_design.id)
  end

  def new
    @design = Design.new
  end

  def create
    @design = Design.new(params[:design])
    @design.save
    redirect_to user_designs_path(@design)
  end

  def show
    @design = Design.find(params[:id])
  end

  private

  def design_params
    params.require(:design).permit(:name, :stretgy, :authority, :non_soi)
  end
end

app/controllers/new_designs_controller.rb
require 'open-uri'
require 'json'

class NewDesignsController < ApplicationController

  def new_design

    url = "https://api.bodygraphchart.com/v221006/hd-data?api_key=#{ENV["API_KEY"]}&date=#{params[:year]}-#{params[:month]}-#{params[:day]}-#{params[:hour]}-#{params[:minutes]}"
    design = JSON.parse(URI.open("#{url}").read)


    strategy = design["Properties"]["Strategy"]["id"]
    type = design["Properties"]["Type"]["id"]
    authority = design["Properties"]["InnerAuthority"]["id"]
    notself = design["Properties"]["NotSelfTheme"]["id"]

  design_from_api = Design.new(name_type: type, strategy: strategy, authority: authority, notself: notself )

    if design_from_api.save

      redirect_to design_show_path(design_from_api)
    else
      render :form_without_design
    end
  end

    def form_without_design
      @design = Design.new
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def informations
  end
end

app/controllers/user_challenges_controller.rb
class UserChallengesController < ApplicationController
  def index
    @userchallenges = UserChallenge.all
  end

  def show
    @userchallenge = UserChallenge.find(params[:id])
  end

  def status
    @userchallenge = UserChallenge.find(params[:id])
    if params[:status].present? && UserChallenge::STATUSES.include?(params[:status].to_sym)
      @userchallenge.update(status: params[:status])
    end
    redirect_to user_challenge_path(@userchallenge)
  end
end

app/controllers/user_designs_controller.rb
class UserDesignsController < ApplicationController
  def index
    @userdesigns = UserDesign.all
  end

  def show
    @user_design = UserDesign.find(params[:id])

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = current_user
  end

  def update
    raise
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/designs/form.html.erb
<div class="container">
  <div class="form-center trans-cards px-2">

    <h2 class="p-2">Fais ton Design Humain</h2>
    <%= form_with url: form_design_path, method: :post do %>
<%# ATTENTION FORMAT DATE ET HEURE %>
      <div class="form-name mb-2">
      <p>Nom</p>
        <%= text_field_tag :name,
              params[:name],
              class: "form-control text-center fw-bold w-100% round-input",
              placeholder: "Jane Doe"
          %>
      </div>

        <div class="form-date">
                <div class="form-day">
                  <p>Jour</p>
                  <%= text_field_tag :day,
                        params[:day],
                        class: "form-control text-center fw-bold round-input",
                        placeholder: "08"
                    %>
                </div>
                <div class="form-month">
                <p>Mois</p>
                  <%= text_field_tag :month,
                        params[:month],
                        class: "form-control text-center fw-bold round-input",
                        placeholder: "06"
                    %>
                </div>
                <div class="form-year">
                <p>Année</p>
                  <%= text_field_tag :year,
                        params[:year],
                        class: "form-control text-center fw-bold round-input",
                        placeholder: "1980"
                    %>
                </div>
        </div>
            <div class="form-birth mt-3">
              <div class="form-hour">
              <p>Heure</p>
                <%= text_field_tag :hour,
                      params[:hour],
                      class: "form-control text-center fw-bold round-input",
                      placeholder: "08"
                  %>
              </div>
              <div class="form-min">
              <p>Minutes</p>
                <%= text_field_tag :minutes,
                      params[:minutes],
                      class: "form-control text-center fw-bold round-input",
                      placeholder: "15"
                  %>
              </div>
          </div>
            <div class="form-city mt-3">
            <p>Lieu de naissance</p>
                    <%= text_field_tag :city,
                        params[:city],
                        class: "form-control text-center fw-bold round-input",
                        placeholder: "Paris"
                    %>
            </div>
        <%= submit_tag "Générer mon Design Humain !", name: "", class: "btn-purple mt-4 text-center w-100 mb-3" %>
              <% end %>

  </div>
</div>

app/views/designs/new.html.erb
<%= simple_form_for @user do |f| %>

<%= f.input :city %>
<%= f.button :submit %>

<% end %>

app/views/designs/show.html.erb
<div class="container" data-controller="audios" data-path="<%= asset_path("sound.mp3") %>">
  <h1> Le Design Humain de votre ami </h1>

  <div class="image-design">
    <p>Design Humain</p>

    <%= image_tag "https://imagizer.imageshack.com/img924/6677/YtUAGl.png", class:"image-design" %>
  </div>

    <div class="info-for-design">
      <div class="audio-centered"><i class="fa-solid fa-circle-play btn-lecture" data-action="click->audios#play"></i><p> <strong> Type: </strong>  <%= @design.name_type %>  </p></div>
      <div class="audio-centered"><i class="fa-solid fa-circle-play btn-lecture" data-action="click->audios#play"></i><p> <strong> Stratégie: </strong>  <%= @design.strategy %> </p></div>
      <div class="audio-centered"><i class="fa-solid fa-circle-play btn-lecture" data-action="click->audios#play"></i><p> <strong> Autorité: </strong> <%= @design.authority %>  </p></div>
      <div class="audio-centered"><i class="fa-solid fa-circle-play btn-lecture" data-action="click->audios#play"></i><p> <strong> Thème du Non Soi : </strong>  <%= @design.notself %> </p></div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> LetUsElevate</title>
      <meta name="apple-mobile-web-app-capable" content="yes">
      <meta name="mobile-web-app-capable" content="yes">
        <%= favicon_link_tag "favicon.png", rel: "icon", type: "image/png" %>
        <title><%= meta_title %></title>
        <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
        <%= render 'shared/ios_pwa_links' %>
    <!-- debut des meta tags reseaux sociaux -->

    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="background">
      <%= render "shared/navbar_top" %>
      <%= yield %>
      <%= render "shared/navbar" %>
    </div>
  </body>
</html>

app/views/new_designs/form_without_design.html.erb
<div class="container">
  <div class="form-center trans-cards px-2">

    <h2 class="p-3">Faites le Design Humain de vos amis !</h2>
    <%= form_with url: try_design_post_path, method: :post do %>
<%# ATTENTION FORMAT DATE ET HEURE %>
      <div class="form-name mb-2">
      <p>Nom</p>
        <%= text_field_tag :name,
              params[:name],
              class: "form-control text-center fw-bold w-100% round-input",
              placeholder: "Jane Doe"
          %>
      </div>

        <div class="form-date">
                <div class="form-day">
                  <p>Jour</p>
                  <%= text_field_tag :day,
                        params[:day],
                        class: "form-control text-center fw-bold round-input",
                        placeholder: "08"
                    %>
                </div>
                <div class="form-month">
                <p>Mois</p>
                  <%= text_field_tag :month,
                        params[:month],
                        class: "form-control text-center fw-bold round-input",
                        placeholder: "06"
                    %>
                </div>
                <div class="form-year">
                <p>Année</p>
                  <%= text_field_tag :year,
                        params[:year],
                        class: "form-control text-center fw-bold round-input",
                        placeholder: "1980"
                    %>
                </div>
        </div>
            <div class="form-birth mt-3">
              <div class="form-hour">
              <p>Heure</p>
                <%= text_field_tag :hour,
                      params[:hour],
                      class: "form-control text-center fw-bold round-input",
                      placeholder: "08"
                  %>
              </div>
              <div class="form-min">
              <p>Minutes</p>
                <%= text_field_tag :minutes,
                      params[:minutes],
                      class: "form-control text-center fw-bold round-input",
                      placeholder: "15"
                  %>
              </div>
          </div>
            <div class="form-city mt-3">
            <p>Lieu de naissance</p>
                    <%= text_field_tag :city,
                        params[:city],
                        class: "form-control text-center fw-bold round-input",
                        placeholder: "Paris"
                    %>
            </div>
        <%= submit_tag "Générer un Design Humain !", name: "", class: "btn-purple mt-4 text-center w-100 mb-3" %>
              <% end %>

  </div>
</div>

app/views/pages/home.html.erb
  <div class="container">
    <div class="info-home">
      <h1 class="LUE">  Let Us Elevate </h1>
      <p class="slogan"> Les je sont faits...Et tout va bien !</p>
      <%= link_to "Découvrir", form_design_path, class:"text-decoration-none" %>
    </div>
  </div>

app/views/pages/informations.html.erb
<div class="container infos">
  <div class="apropos" data-controller="informations">




    <h1 class="text-center mb-4">Informations</h1>
    <div class="info_1 white-back p-5 boxshadow" data-informations-target="info_1">
      <h2 class="text-center">Qu’est-ce que le Design Humain ?</h2>
      <p>Le design humain est un outil de connaissance de soi. Il permet de découvrir son plan de fonctionnement énergétique unique au niveau individuel</p>
    </div>

    <div class="info_2 d-none white-back p-5 mt-4 boxshadow" data-informations-target="info_2">
      <h2 class="text-center">Outil de connaissance inédit</h2>
      <p>Pluridisciplinaire dans sa structure, le design humain se base sur :</p>
      <ul>
        <li>L'astrologie</li>
        <li>Le système des chakras</li>
        <li>Le système de la Kabbale</li>
        <li>La physique quantique et génétique</li>
      </ul>
    </div>


    <div class="btns-info">
    <i data-action="click->informations#first" data-informations-target="btn_1" class="fa-solid fa-circle info-active"></i>
    <i data-action="click->informations#second" data-informations-target="btn_2" class="fa-solid fa-circle"></i>
    </div>

  </div>






</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar-lewagon">
  <% if current_user %>
    <%# Si le user a deja un design on le redirige dessus %>
    <% if current_user.user_design %>
      <%= link_to user_design_path(current_user.user_design), class: "navbar-brand" do %>
        <i class="fa-solid fa-moon"></i>
        <p>Mon design</p>
      <% end %>
    <% else %>
        <%# sinon on redirige vers le formulaire %>
      <%= link_to form_design_path, class: "navbar-brand" do %>
        <i class="fa-solid fa-moon"></i>
        <p>Mon design</p>
      <% end %>
    <% end %>
  <% end %>

  <%= link_to user_challenges_path, class: "navbar-brand" do%>
    <i class="fa-solid fa-star"></i>
    <p>Mes challenges</p>
  <% end %>

  <%= link_to try_design_path, class: "navbar-brand" do %>
    <i class="fa-solid fa-earth-europe"></i>
    <p>Explorer</p>
  <% end %>

  <%= link_to informations_path, class: "navbar-brand"  do %>
    <i class="fa-solid fa-circle-info hw" style="color: #ffffff;"></i>
    <p>Informations</p>
  <% end%>
</div>

app/views/shared/_navbar_top.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand-top" do %>
      <%= image_tag "logo-LetUE.png", class:"top-nav" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item dropdown text-center">
            <%= image_tag "https://static.thenounproject.com/png/4035892-200.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu background-nav dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%#= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>



        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/user_challenges/index.html.erb
<div class="container font-size-chall">
    <div class="text-white m-2 pb-4">
      <h1>Mes challenges</h1>
    </div>
        <% @userchallenges.each do |challenge| %>
      <div class="trans-back m-3 challenge-content p-2 font-family: inherit;">
        <%= link_to challenge.challenge.title, user_challenge_path(challenge), class:"text-decoration-none text-black f-size-index" %>
      </div>
        <% end %>
</div>

app/views/user_challenges/show.html.erb
<div class="container img">
  <div class="space"></div>
  <div class="show-content-challenges">
    <div class="trans-back-blue">
      <h1 class="challenge-content">Challenge</h1>
       <h2><%= @userchallenge.challenge.title %></h2>
    </div>
      <div class="trans-back chal-desc">
        <p><%= @userchallenge.challenge.description %></p>
      </div>

      <div class="trans-back text-center">
          <% if @userchallenge.status == nil %>
            <p>Vous n'avez pas encore tenté ce challenge, il est l'heure !</p>
              <div class="emote-btn">
                <%= link_to change_status_user_challenge_path(@userchallenge, status: "nul"), data: { turbo_method: :patch} do %>
                  <i class="fa-solid fa-circle-xmark" style="color: #000000;"></i>
                <% end %>
                <%= link_to change_status_user_challenge_path(@userchallenge, status: "moyen"), data: { turbo_method: :patch} do %>
                  <i class="fa-solid fa-circle-half-stroke" style="color: #000000;"></i>
                <% end %>
                <%= link_to change_status_user_challenge_path(@userchallenge, status: "réussi"), data: { turbo_method: :patch} do %>
                  <i class="fa-solid fa-circle-check" style="color: #000000;"></i>
                <% end %>
              </div>
          <% elsif @userchallenge.status == "nul" %>
                <p>La dernière fois, vous ne vous sentiez pas en accord avec vous même ! Retentez l'expérience</p>
                  <div class="emote-btn">
                    <%= link_to change_status_user_challenge_path(@userchallenge, status: "moyen"), data: { turbo_method: :patch} do %>
                      <i class="fa-solid fa-circle-half-stroke" style="color: #000000;"></i>
                    <% end %>
                    <%= link_to change_status_user_challenge_path(@userchallenge, status: "réussi"), data: { turbo_method: :patch} do %>
                      <i class="fa-solid fa-circle-check" style="color: #000000;"></i>
                    <% end %>
                  </div>
          <% elsif @userchallenge.status == "moyen" %>
                <p>La dernière fois, vous vous sentiez mitigé, retentez l'expérience !</p>
                  <div class="emote-btn">
                    <%= link_to change_status_user_challenge_path(@userchallenge, status: "nul"), data: { turbo_method: :patch} do %>
                      <i class="fa-solid fa-circle-xmark" style="color: #000000;"></i>
                    <% end %>
                    <%= link_to change_status_user_challenge_path(@userchallenge, status: "réussi"), data: { turbo_method: :patch} do %>
                      <i class="fa-solid fa-circle-check" style="color: #000000;"></i>
                    <% end %>
                  </div>
          <% elsif @userchallenge.status == "réussi" %>
              <p class="">Bravo ! Vous avez fait un beau pas vers votre élévation. Place à la suite !</p>
          <% end %>

            <div class="mt-4 mb-2">
            </div>
      </div>
  </div>
</div>

app/views/user_designs/index.html.erb
<div class="container">

  <h1>Mon Design</h1>
  <% @userdesigns.each do |userdesign| %>

 <%= image_tag "https://imagizer.imageshack.com/img924/8678/xdEd92.png", class:"image-design" %>

    <div> Type <%= userdesign.design.name_type %></div>
    <div> Strategy <%= userdesign.design.strategy %></div>
    <div> Authority <%= userdesign.design.authority %></div>
    <div> Not Self theme <%= userdesign.design.notself %></div>

  <% end %>

  <%= link_to "challenges", user_challenges_path %>
</div>

app/views/user_designs/newdesign.html.erb
<h1 class="let us elevate"> Let Us Elevate </h1>


  <div class="text-block">


      <i class="fa-solid fa-moon"> Mon design </i>
    </div>



    <%= image_tag "https://imagizer.imageshack.com/img924/8678/xdEd92.png", class:"image-design" %>

    <div class="trans-back-vic">

      <div> <p> Type : <%= @design.name_type %>  </p> </div>
      <div> <p> Strategie : <%= @design.strategy %>  </p> </div>
      <div> <p> Autorité : <%= @design.design.authority %>  </p> </div>
      <div> <p> Thème du Non Soi : <%= @design.design.notself %> </p> </div>
    </div>
  </div>

app/views/user_designs/show.html.erb
<div class="container" data-controller="audios" data-path="<%= asset_path("sound.mp3") %>">
  <h1> Votre Design Humain </h1>

  <div class="image-design">
    <p><%= current_user.username ? current_user.username : "Votre Design" %></p>
    <%= image_tag "https://imagizer.imageshack.com/img924/6677/YtUAGl.png", class:"image-design" %>
  </div>



  <div class="info-for-design">
    <div class="audio-centered"><i class="fa-solid fa-circle-play btn-lecture" data-action="click->audios#play"></i><p> <strong> Type: </strong>  <%= @user_design.design.name_type %>  </p></div>
    <div class="audio-centered"><i class="fa-solid fa-circle-play btn-lecture" data-action="click->audios#play"></i><p> <strong> Stratégie: </strong>  <%= @user_design.design.strategy %> </p></div>
    <div class="audio-centered"><i class="fa-solid fa-circle-play btn-lecture" data-action="click->audios#play"></i><p> <strong> Autorité: </strong> <%= @user_design.design.authority %>  </p></div>
    <div class="audio-centered"><i class="fa-solid fa-circle-play btn-lecture" data-action="click->audios#play"></i><p> <strong> Thème du Non Soi : </strong>  <%= @user_design.design.notself %> </p></div>
  </div>

</div>

app/views/users/edit.html.erb
<p>test</p>


<%= simple_form_for @user do |f| %>

<%= f.input :city %>
<%= f.button :submit %>

<% end %>